### ISSUE TITLE
Better way to wait for dnsmasq restart completion?

### ISSUE THREAD

**Issue by lynxthecat** [lynxthecat/adblock-lean#12]
Right now we simply issue a `sleep 10` call to wait for a dnsmasq restart before checking the new dnsmasq instance - see here:

https://github.com/lynxthecat/adblock-lean/blob/90f3d50f48656af4c2667cdb46a0faca9bc65311/adblock-lean#L217

This is rather crude. 

Surely there is a better way to wait until the dnsmasq restart has completed to avoid waiting unnecessarily long or, worse, not long enough?

@dave14305 and @Wizballs, any thoughts?

**Comment by Wizballs** [comment]
Actually have been thinking about this also.  Something along the lines of checking eg every second for a dnsmasq finished code (if something exists?}.   Or possibly reading system log looking for a certain text string?

**Comment by lynxthecat** [comment]
It seems dnsmasq writes to the system logger:

```
Mon Jun  5 05:47:22 2023 user.notice adblock-lean: Downloading new blocklist file part from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/pro.txt.
Mon Jun  5 05:47:47 2023 user.notice adblock-lean: Download of new blocklist file part from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/pro.txt suceeded.
Mon Jun  5 05:48:15 2023 user.notice adblock-lean: Restarting dnsmasq.
Mon Jun  5 05:48:15 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: started, version 2.86 cachesize 150
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: DNS service limited to local subnets
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack no-ipset no-auth no-cryptohash no-DNSSEC no-ID loop-detect inotify dumpfile
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.2.100 -- 192.168.2.249, lease time 12h
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#5453
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using nameserver ::1#5453
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using only locally-known addresses for test
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using only locally-known addresses for local
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using only locally-known addresses for zzztt49.com
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using only locally-known addresses for zzznews.ru
Mon Jun  5 05:48:23 2023 daemon.info dnsmasq[1]: using 405198 more local addresses
Mon Jun  5 05:48:26 2023 daemon.info dnsmasq[1]: read /etc/hosts - 4 addresses
Mon Jun  5 05:48:26 2023 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
Mon Jun  5 05:48:26 2023 daemon.info dnsmasq[1]: read /tmp/hosts/odhcpd - 0 addresses
Mon Jun  5 05:48:26 2023 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Mon Jun  5 05:48:31 2023 user.notice adblock-lean: Checking dnsmasq instance.
Mon Jun  5 05:48:32 2023 user.notice adblock-lean: The dnsmasq check passed with new blocklist file.
```

But actually - check out how the restart took longer than 10 seconds but the check did not occur until after the restart. 

So actually perhaps we don't need to do anything other than delete the `sleep 10` because `/etc/init.d/dnsmasq restart &> /dev/null` already blocks for the requisite time?

**Comment by Wizballs** [comment]
I was hoping the removal of sleep 10 would be the easy 'fix' but unfortunately: 
Tue Jun  6 06:12:06 2023 user.notice adblock-lean: Lookup of 'google.com' failed with new blocklist.
This is probably the reason for Bill's issue (on Openwrt forum), sleep 20, or even sleep 30 might not be enough for slower routers....

PS yep pretty quick overall, and yep if using just one blocklist completes in under one minute...

**Comment by Wizballs** [comment]
How about do the dnsmasq checking of google.com microsoft.com amazon.com every eg 3 seconds for a maximum of 20 iterations (so eg max 60 seconds).  Once one loop passes, then everything is ok.  If at the end of 20 iterations and they are still not reachable, then clear the blocklist and restart dnsmasq.

**Comment by dave14305** [comment]
My preference is to check the dnsmasq syntax before restarting dnsmasq.

```
# Test if dnsmasq has any problems with the new blocklist before promoting it to the live blocklist
if dnsmasq --test --conf-file=/tmp/blocklist >/dev/null 2>&1; then
  mv /tmp/blocklist /tmp/dnsmasq.d/blocklist
  log_msg "Restarting dnsmasq."
  /etc/init.d/dnsmasq restart &> /dev/null
else
  log_msg "The dnsmasq check failed with new blocklist file."
fi
```

**Comment by Wizballs** [comment]
if dnsmasq --test --conf-file=/tmp/blocklist >/dev/null 2>&1; then
That's a great check to add in addition to the current.

I think @lynxthecat intention is to check that a few major site can actually be accessed, not just testing that all inputs/syntax is correct.  Ie scenario that a blocklist accidentally adds any one of these three entries as blocked.  Unlikely, but possible...

**Comment by lynxthecat** [comment]
That syntax check looks helpful though. Might as well add that in too on our blocklist process and check function, as a final step.

But yes, how to wait and block until dnsmasq has fully restarted?

**Comment by Wizballs** [comment]
Yes I agree add the syntax check before restarting dnsmasq.  I think what is happening (unsure?) is that dnsmasq is restarting to a certain point and then the next steps in the bash script continue running.  But even after that more dnsmasq stuff is still going on, you can see it in the log.

I can't find any dnsmasq option that will help report when it's fully loaded.  No matter what testing is performed, if I take out the sleep 10, then nslookup fails.  There is that iteration method I posted above, but yep feels like a cheap workaround.  

Maybe put in an option into the config section eg 'perform_nslookup=1' and if user edits that to '0' then skip that check?

**Comment by lynxthecat** [comment]
For now I've incorporated a final check to process_and_check_blocklist_file() with https://github.com/lynxthecat/adblock-lean/commit/67fe05eb27c54d7058cdf6bb426dfedec65f41c5. 

I'm hoping that @dave14305 has a good idea about how to properly wait on the dnsmasq service restart for dnsmasq to be fully up and running.

**Comment by lynxthecat** [comment]
@Wizballs does this work for you:

```
service dnsmasq restart; for retries in {1 .. 60}; do if nslookup localhost.lan 127.0.0.1; then break; else echo "not up yet"; sleep 1; fi done; nslookup google.com
```

**Comment by Wizballs** [comment]
Yep i think that is good for now, until/if a better solution can be found.  IMO opinion every second is a little excessive and a few seconds in between won't have any real world impact.

Also, I think move the sleep command to the left/first so that even the first iteration has the sleep command before nslookups.

That was quick work, I'll be able to test it soon tonight

**Comment by lynxthecat** [comment]
OK I've added the fix: https://github.com/lynxthecat/adblock-lean/commit/37c573e1f236af69a7cfef42e8cb93a8f7e85ba6. 

I've kept the check first and sleep 1 because I want adblock-lean to complete as quickly as possible for any comparisons with any competing implementation.

**Comment by dave14305** [comment]
> It restarts and then blocks until `nslookup localhost.lan 127.0.0.01` returns true, which is about two seconds on my system.

You shouldn’t assume everyone’s local domain is `.lan`. Mine isn’t.

> I'm hoping that @dave14305 has a good idea about how to properly wait on the dnsmasq service restart for the new dnsmasq to be fully up and running.

There doesn’t seem to be a foolproof method that is obvious yet.

**Comment by lynxthecat** [comment]
> You shouldn’t assume everyone’s local domain is `.lan`. Mine isn’t.

Ah, what would be a better generic check for that?

**Comment by dave14305** [comment]
```
root@router:~# nslookup localhost. 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1:53

Name:   localhost
Address: 127.0.0.1

Name:   localhost
Address: ::1
```

**Comment by lynxthecat** [comment]
Is localhost OK without the dot?

```
root@OpenWrt-1:~/cake-autorate# nslookup localhost 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1:53

Name:   localhost
Address: 127.0.0.1

Name:   localhost
Address: ::1
```

**Comment by Wizballs** [comment]
@lynxthecat Well just gave it a run-thru with the 
for i in $(seq 1 60)
	do
		nslookup localhost 127.0.0.1 &> /dev/null && break
		sleep 1;

Thats seems like quite a clean method and worked well..

Also yes agree, maximum speed :)  Some balance is ok, but speed is always nice.

**Comment by Wizballs** [comment]
I just gave the master branch a run and all is good with those updates.  I'll jump on Openwrt forum and let Bill know so he can try the latest script.

**Comment by dave14305** [comment]
I found this interesting syntax used in some other scripts:
```
ubus -t 10 wait_for dnsmasq
```
This will wait up to 10 seconds for dnsmasq to register with ubus.

**Comment by lynxthecat** [comment]
Seems promising. Do you think that's preferable to what we settled on?

**Comment by lynxthecat** [comment]
@Wizballs is this the change you have in mind:

```
root@OpenWrt-1:/tmp/adblock-lean# git diff
diff --git a/adblock-lean b/adblock-lean
index 537b6a2..0e5a406 100755
--- a/adblock-lean
+++ b/adblock-lean
@@ -282,11 +282,7 @@ restart_dnsmasq()

        /etc/init.d/dnsmasq restart &> /dev/null

-       for i in $(seq 1 60)
-       do
-               nslookup localhost 127.0.0.1 &> /dev/null && break
-               sleep 1;
-       done
+       ubus -t 60 wait_for dnsmasq

        log_msg "Restart of dnsmasq completed."
 }
```

**Comment by Wizballs** [comment]
Yep looks good.  I was just floating the idea for check on boot really.  I'm not sure what order services etc start.  Ie is there any risk on any configuration that lean start a bit early, before the rest of the router finishes booting up?

**Comment by lynxthecat** [comment]
> I'm not sure what order services etc start. Ie is there any risk on any configuration that lean starts a bit early, before the rest of the router finishes booting up?

I don't think so, because the init.d order is set with:

```
START=99
STOP=4
```

Which means don't start until pretty much all the other services have already started, but stop before most other services have been stopped - see:

https://openwrt.org/docs/techref/initscripts

**Comment by Wizballs** [comment]
Ah right yes I see the start number logic now.  Thanks for the explanation

**Comment by lynxthecat** [comment]
OK gents, I've made the substitution for the ubus call with: commit: https://github.com/lynxthecat/adblock-lean/commit/be8110bee7b1c961ef92ef731baef9bfa1af6897.
