### ISSUE TITLE
Rogue Element identified in new blocklist

### ISSUE THREAD

**Issue by shown19** [lynxthecat/adblock-lean#15]
Hi noob question, may I know why I'm getting this error, what  does rogue element means?

`
Rogue element: '447216: local=/antonio' identified in new blocklist.
`

By the way, I'm using hagezi blocklist. The rest of his blocklist are working but if I include the threat intelligence feed dnsmasq link provided, I got that error. Is this a compatibility issue?

**Comment by hagezi** [comment]
The message must come from another block list, my lists do not contain ` local=`:

`curl -sL https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/dnsmasq/tif.txt | sed -n '447216p'`

`address=/inov2elate.com/#`

**Comment by shown19** [comment]
@hagezi  Wow, I get it now, coz I'm also using your hagezi pro so maybe this is the reason, right? it all make sense now. Thank you and for your fast response, appreciate it.  :)

**Comment by hagezi** [comment]
The Pro also does not contain a `local=` element.

**Comment by lynxthecat** [comment]
Hey @hagezi, plenty from the OpenWrt community now use your list, and this little 'adblock-lean' service script has proved fairly popular - see: https://forum.openwrt.org/t/adblock-lean-set-up-adblock-using-dnsmasq-blocklist/157076.

**Comment by hagezi** [comment]
I don't know if the `address=/` elements are converted to `local=/` during import and something goes "wrong".

**Comment by lynxthecat** [comment]
@shown19 a suggestion was put forward [here](https://forum.openwrt.org/t/adblock-lean-set-up-adblock-using-dnsmasq-blocklist/157076/223?u=lynx). Namely it could be that the head -c is truncating your blocklist part download.  Is the blocklist file part larger than 20MB? If so, consider inreasing:

```
	# Maximum size of any individual downloaded blocklist part
	max_blocklist_file_part_size_KB=20000
```

**Comment by shown19** [comment]
> The Pro also does not contain a `local=` element.

@hagezi  weird, but I only used your lists

@lynxthecat I set max_blocklist_file_part_size_KB from 20000 to 50000 to 100000 just to test but still got an error unless i remove the threath intelligence feed and it's working again.


this is the list I am using:
```
blocklist_urls="https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/pro.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/doh-vpn-proxy-bypass.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/dyndns.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/hoster.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.amazon.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.apple.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.huawei.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.winoffice.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.tiktok.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.tiktok.extended.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/native.lgwebos.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/tif.txt --> successful if this is remove
```


restarting adblock-lean outputted this, maybe there's a hint here?

```

Downloading new blocklist file part from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/tif.txt.
Download of new blocklist file part from: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/tif.txt suceeded (downloaded file size: 28162 KB).
Cleaning whitespace and formatting blocklist file part as local=/.../.
sed: write error
Successfully generated preprocessed blocklist file with 465097 line(s).
Processing and checking new blocklist file.
Preprocessed blocklist file size: 13080 KB.
Removing duplicates from blocklist file.
Duplicates removed.
Found local allowlist with 38 lines.  Removing (sub)domain matches from blocklist.
Removal of allowlist (sub)domain matches from blocklist complete.
Checking for any rogue elements.
Rogue element: '447847: local=' identified in new blocklist.
New blocklist file check failed.

```

**Comment by hagezi** [comment]
> @shown19 a good suggestion was put forward [here](https://forum.openwrt.org/t/adblock-lean-set-up-adblock-using-dnsmasq-blocklist/157076/223?u=lynx). Namely it could be that the `head -c` call [here](https://github.com/lynxthecat/adblock-lean/blob/c12cf5f95c2a9a9c225da087329488f9de741243/adblock-lean#L137) is truncating your blocklist file part download. Is the blocklist file part larger than 20MB? If so, consider increasing the following value in your config file:
> 
> ```
> 	# Maximum size of any individual downloaded blocklist part
> 	max_blocklist_file_part_size_KB=20000
> ```

Yes, that will be the problem, the TIF is ~30MB.

**Comment by lynxthecat** [comment]
This looks problematic:
```
sed: write error
```

**Comment by lynxthecat** [comment]
Are you sure you have sufficient available free memory (try with free -m)?

**Comment by shown19** [comment]
@lynxthecat  I think so, here's the output:

```
root@Openwrt:~# free -m
              total        used        free      shared  buff/cache   available
Mem:         444464       52924      186108      180984      205432      173760
Swap:             0           0           0

```

**Comment by lynxthecat** [comment]
@dave14305 any ideas here?

**Comment by dave14305** [comment]
/tmp is generally only half the size of free memory. Probably just too many lists.

**Comment by shown19** [comment]
Anyway, if it's complicated then I will not be forcing this TIF list and I think this other lists of hagezi are enough for my needs already so thank you very much guys for all the help @lynxthecat @dave14305  @hagezi

**Comment by lynxthecat** [comment]
You're welcome. I think I might try to add a check for truncation based on the `head -c` call.

**Comment by lynxthecat** [comment]
Done: https://github.com/lynxthecat/adblock-lean/commit/7ba953d660a27340024234c38fe0c9993e98a41b.
