### ISSUE TITLE
how to change Upstream DNS

### ISSUE THREAD

**Issue by icountu** [lynxthecat/adblock-lean#18]
Thanks for creating Adblock-lean. How to test; if it s working on lan side or not and I'm also wondering if there is way to change upstream encrypted or non encrypted DNS?

**Comment by lynxthecat** [comment]
Sorry for the late response. If you still need help with this I suggest posting here:

https://forum.openwrt.org/t/adblock-lean-set-up-adblock-using-dnsmasq-blocklist/157076
