### ISSUE TITLE
TIF - Block IPs with DNSmasq - `bogus-nxdomain=1.2.3.4`

### ISSUE THREAD

**Issue by hagezi** [lynxthecat/adblock-lean#23]
Hi @lynxthecat,

could you add support and test my TIF IP list in DNSmasq format in adblocklean?

`bogus-nxdomain=1.2.3.4`
All domains resolving to the "blocked" IP should be answered with NXDOMAIN.

The list:
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/tif-ips.txt

Thank you,
Gerd

**Comment by lynxthecat** [comment]
Dear @hagezi,

What would the corresponding entries in the dnsmasq blocklist look like?

Or @Wizballs perhaps you have an idea here?

Kind regards,

@lynxthecat

**Comment by hagezi** [comment]
@lynxthecat `bogus-nxdomain=1.2.3.4` is the DNSmasq syntax, But I don't know if you can mix this with the local entries in a file. You would have to test that.

**Comment by lynxthecat** [comment]
Testing now..

**Comment by lynxthecat** [comment]
@hagezi testing now. How can I test this with your test file once dnsmasq has been restarted? Can you give me an example lookup?

**Comment by lynxthecat** [comment]
Does this indicate it is working:

``
root@OpenWrt-1:~# nslookup server-99-84-47-183.ewr52.r.cloudfront.net
Server:         127.0.0.1
Address:        127.0.0.1:53

** server can't find server-99-84-47-183.ewr52.r.cloudfront.net: NXDOMAIN

Non-authoritative answer:
```

**Comment by hagezi** [comment]
>How can I test this with your test file once dnsmasq has been restarted? Can you give me an example lookup?

Determine the IPs of e.g. reddit.com (`dig reddit.com`), block them with `bogus-nxdomain` and then try to resolve `reddit.com`. a dig should then return an NXDOMAIN as status.

**Comment by Wizballs** [comment]
Alrighty, bogus-nxdomain=xx.xx.xx now allowed (details in main openwrt thread).  I've added this to my default lists due to the added protection.  Currently 200k lines.

**Comment by lynxthecat** [comment]
Added in https://github.com/lynxthecat/adblock-lean/commit/09ed8638fa814cfd84ec565971ae786ef516d0fc. New defaults for the blocklist file parts are: 

```
blocklist_urls="https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/pro.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/tif-ips.txt"
```
