### ISSUE TITLE
Allowlist - Which syntax/format is supported?

### ISSUE THREAD

**Issue by hagezi** [lynxthecat/adblock-lean#24]
Hi @lynxthecat,

I had a request to provide my referral allowlist for adblocklean. As it is a wildcard list, it is currently only available in AdBlock format, see: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt

Which format/syntax is supported by adblocklean?

The lists contains rules like `track*.example.com` and the rule `example.com` unblocks `example.com` and all subdomains (`*.example.com`). How can this be mapped for adblocklean?

Thanks,
Gerd

**Comment by lynxthecat** [comment]
@Wizballs how does our allowlist format work again? I know we recently expanded it to work with subdomains.

**Comment by Wizballs** [comment]
Hi Hazezi, lynx,

adblock-lean has allowlist implemented in the following way:

- example.com and all subdomains such as *.example.com are deleted from the blocklist
- and a positive allow entry is added server=/example.com/#  (this is to allow cases for example where example.com is blocked along with all subdomains, but the user wishes to unblock only one.example.com and leave all other example.com blocked)

I'll have to do some trials on dnsmasq wildcard handling over say the next 24 hours.  but dnsmasq seems to accept them at least:
root@OpenWrt:~# dnsmasq --test --conf-file=/tmp/dnsmasq.d/blocklist
dnsmasq: syntax check OK.

**Comment by hagezi** [comment]
DNSmasq only processes a * if it is at the beginning of a domain, not within and not at the end.

**Comment by lynxthecat** [comment]
> It would be good if the user also had the option of downloading allowlists, as with the blocklists.

I have almost completed this now:

https://github.com/lynxthecat/adblock-lean/compare/master...add-allowlist_urls

https://forum.openwrt.org/t/adblock-lean-set-up-adblock-using-dnsmasq-blocklist/157076/940

**Comment by lynxthecat** [comment]
Pretty much there now: https://github.com/lynxthecat/adblock-lean/commit/68b11ba119810387eed5f8018313682ebdfab5a7. Seems to be working for me.
