### ISSUE TITLE
Syntax error during gen_config

### ISSUE THREAD

**Issue by rougeSE** [lynxthecat/adblock-lean#53]
During the generation of default configuration file per the install instruction. there is a syntax error as follows using the shell version BusyBox v1.28.4 () built-in shell (ash)

root@router:# wget https://raw.githubusercontent.com/lynxthecat/adblock-lean/main/adblock-lean -O /etc/init.d/adblock-lean
--2024-07-27 15:00:57--  https://raw.githubusercontent.com/lynxthecat/adblock-lean/main/adblock-lean
Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28560 (28K) [text/plain]
Saving to: '/etc/init.d/adblock-lean'

/etc/init.d/adblock-lean               100%[============================================================================>]  27.89K  66.2KB/s    in 0.4s    

2024-07-27 15:00:58 (66.2 KB/s) - '/etc/init.d/adblock-lean' saved [28560/28560]

root@router:# chmod +x /etc/init.d/adblock-lean
root@router:# service adblock-lean gen_config
/etc/rc.common: /etc/init.d/adblock-lean: line 337: syntax error: unexpected "("

**Comment by Wizballs** [comment]
Hello what Openwrt version are you using?
busybox 1.28.4 seems from an older release judging from this table:

18.06.1 | 1.28.3
18.06.2 | 1.28.4
18.06.3 | 1.28.4
18.06.4 | 1.28.4
18.06.5 | 1.28.4
19.07.0 | 1.30.1

Currently 23.05.4 has busybox 1.36.1-1

**Comment by friendly-bits** [comment]
Indeed, the line in question is invoking process substitution with syntax `<(command)`. Process substitution support was added to Busybox ash in version 1.34.

> https://www.busybox.net/

**Comment by lynxthecat** [comment]
@antonk is this issue still present or did you swap this out with the POSIX changes I wonder?

**Comment by friendly-bits** [comment]
You tagged somebody else :)
And this issue is still present, we are relying on process substitution for splitting the pipe with tee. So I think this can be resolved as 'won't fix'.
