### ISSUE TITLE
Pause and Resume  broken

### ISSUE THREAD

**Issue by rickparrish** [lynxthecat/adblock-lean#54]
I was just about to add Pause and Resume buttons to the luci app, but they appear to be broken for me.

Looking at the code, I see Pause exports the existing blocklist to `/var/run/adblock-lean/prev_blocklist.gz`, but then the trap runs `rm -rf /var/run/adblock-lean` on exit, so the exported blocklist is deleted and then of course Resume can't find it to restore it.

Should Pause and Resume use an alternate location that isn't wiped, like `/tmp/adblock-lean/prev_blocklist.gz`?

**Comment by friendly-bits** [comment]
It's good that you found this. Clearly the trap should not be universally applied at every call to every function. As soon as the POSIX syntax commit is merged, I'll get to work on the trap and lock file improvements. These 2 things are related, so I'll tackle them together.

**Comment by friendly-bits** [comment]
Fixed by PR #56 , we can close this issue.
