### ISSUE TITLE
Error relating to free RAM detection

### ISSUE THREAD

**Issue by strowi** [lynxthecat/adblock-lean#71]
Hi,

first of all thx for the work put into this. ;)
I stumbled upon the following hard error because of the `free_ram < total_sizes *2` check:

```bash
Sat Aug 24 16:15:26 2024 user.notice adblock-fast [27025]: Starting adblock-fast 1.1.2-3...
Sat Aug 24 16:15:26 2024 user.notice adblock-fast [27025]: ERROR: free ram (60243968) is not enough to process all enabled block-lists!
Sat Aug 24 16:15:27 2024 user.notice adblock-fast [27025]: ERROR: failed to create /var/lib/unbound/adb_list.adblock-fast file!
Sat Aug 24 16:15:27 2024 user.notice adblock-fast [27025]: service failed to start!
```

which is a good default, but a little annoying if you have put root on a USB-stick aka extroot:

```bash
~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 3.8M      3.8M         0 100% /rom
tmpfs                   500.0M     25.0M    475.0M   5% /tmp
/dev/sda1               924.6M    520.7M    340.0M  60% /overlay
overlayfs:/overlay      924.6M    520.7M    340.0M  60% /
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/mtdblock4            2.1M      1.7M    388.0K  82% /rwm
root@ygg:~# free -h
              total        used        free      shared  buff/cache   available
Mem:         122052       41704       32148       25596       48200       18876
Swap:        511996        1952      510044
```

Now i just commented the check inside the script (which will get overwritten with the next update) and it is running fine for quite some time now.
But it might be useful to others to add either the detection of extroot or an option to disable this check?

greetings,
strowi

**Comment by lynxthecat** [comment]
Interesting. Any suggestions for how to modify the check to accommodate for such external storage?

**Comment by strowi** [comment]
Haven't thought about this too deep, but it might be possible to check the free space in the destination directory.. 

`df -P /path/to/directory | tail -1 | awk '{print $4}'`

But i'd be happy with a config variable too.

**Comment by friendly-bits** [comment]
First, I'll point out that this issue is not directly related to adblock-lean but rather a different project named 'adblock-fast".

Second (to @strowi) adblock-fast support is available on the OpenWrt forum.

Third, this project (adblock-lean) doesn't have this check implemented currently, although I'm thinking about implementing something like this.

**Comment by friendly-bits** [comment]
And @lynxthecat you tagged someone else :)

**Comment by strowi** [comment]
@friendly-bits argh you are right. I am so sorry, i mixed them up while testing both...
