### ISSUE TITLE
immortalWRT 21.02.0 /etc/rc.common: /etc/init.d/adblock-lean: line 716: syntax error: unexpected "("

### ISSUE THREAD

**Issue by ly9999999** [lynxthecat/adblock-lean#73]
root@ImmortalWrt:~# uclient-fetch https://raw.githubusercontent.com/lynxthecat/adblock-lean/main/adblock-lean -O /etc/init.d/adblock-lean
Downloading 'https://raw.githubusercontent.com/lynxthecat/adblock-lean/main/adblock-lean'
Connecting to 185.199.108.133:443
Writing to '/etc/init.d/adblock-lean'
/etc/init.d/adblock- 100% |*******************************| 51539   0:00:00 ETA
Download completed (51539 bytes)
root@ImmortalWrt:~# chmod +x /etc/init.d/adblock-lean
root@ImmortalWrt:~# service adblock-lean gen_config   # generates default config in /root/adblock-lean/config
/etc/rc.common: /etc/init.d/adblock-lean: line 716: syntax error: unexpected "("
root@ImmortalWrt:~# uci add_list dhcp.@dnsmasq[0].addnmount='/bin/busybox' && uci commit   # Optional/recommended.  Enables blocklist compression to reduce RAM usage
root@ImmortalWrt:~# service adblock-lean enable   # this will allow the script to automatically run on boot
/etc/rc.common: /etc/init.d/adblock-lean: line 716: syntax error: unexpected "(

root@ImmortalWrt:~# service adblock-lean update
/etc/rc.common: /etc/init.d/adblock-lean: line 716: syntax error: unexpected "("
root@ImmortalWrt:~# service adblock-lean gen_config
/etc/rc.common: /etc/init.d/adblock-lean: line 716: syntax error: unexpected "("

PLEASE tell me how to run adblock-lean.

**Comment by lynxthecat** [comment]
What are you running this on?

**Comment by lynxthecat** [comment]
Ah, either ask the ImmortalWrt developers or switch to OpenWrt.

**Comment by nocmt** [comment]
我也遇到了这个问题，看起来需要改脚本，不支持tee > (...) 这种写法

**Comment by lynxthecat** [comment]
@nocmt doesn't ImmortalWrt use ash?
