### ISSUE TITLE
luci variable renamed

### ISSUE THREAD

**Issue by rickparrish** [lynxthecat/adblock-lean#76]
Awesome work with the latest version!  I've updated the luci app to support the new paths and config format, but ran into one issue where a luci variable was renamed:

https://github.com/lynxthecat/adblock-lean/blob/master/adblock-lean#L2094

That should be `luci_good_line_count` instead of `luci_min_good_line_count`

Aside from that, new version is working great for me!  I didn't think to try doing an upgrade before blowing everything away and starting with a fresh install though.

**Comment by friendly-bits** [comment]
Fixed in the development branch.
