### ISSUE TITLE
ImmortalWrt 21.02.7 dnsmasq-full error 

### ISSUE THREAD

**Issue by hungtoong** [lynxthecat/adblock-lean#77]
root@ImmortalWrt:~# uclient-fetch https://raw.githubusercontent.com/lynxthecat/a
dblock-lean/main/adblock-lean -O /etc/init.d/adblock-lean
Downloading 'https://raw.githubusercontent.com/lynxthecat/adblock-lean/main/adblock-lean'
Connecting to 185.199.109.133:443
Writing to '/etc/init.d/adblock-lean'
/etc/init.d/adblock- 100% |*******************************| 67902   0:00:00 ETA
Download completed (67902 bytes)
root@ImmortalWrt:~# chmod +x /etc/init.d/adblock-lean
root@ImmortalWrt:~# service adblock-lean gen_config   # generates default config in /root/adblock-lean/con
fig
/etc/rc.common: /etc/init.d/adblock-lean: line 990: syntax error: unexpected "("
root@ImmortalWrt:~# uci add_list dhcp.@dnsmasq[0].addnmount='/bin/busybox' && uci commit   # Optional/reco
mmended.  Enables blocklist compression to reduce RAM usage
root@ImmortalWrt:~# service adblock-lean enable   # this will allow the script to automatically run on boo
t
/etc/rc.common: /etc/init.d/adblock-lean: line 990: syntax error: unexpected "("
root@ImmortalWrt:~#

**Comment by lynxthecat** [comment]
ImmortalWrt is not supported. Use OpenWrt. 

See: 

https://github.com/lynxthecat/adblock-lean/issues/73

**Comment by hungtoong** [comment]
Thank u

**Comment by friendly-bits** [comment]
@lynxthecat looking again at the code, there is no critical functionality depending on process substitution. We have 7 instances, with 5 of them implementing counting entries and/or bytes, 1 implementing the rogue elements check and 1 involved in the version update. If we really wanted to support Busybox ash without process substitution, we could add a config option which would essentially disable element count and size checks, and change the code for the update command to get rid of process substitution there.

I don't have a strong opinion on this, and I certainly don't care about ImmortalWrt, but this could potentially make the app compatible with older versions of OpenWrt which some people are still running.

**Comment by lynxthecat** [comment]
Sounds reasonable to me but would it involve a lot of extra coding?

**Comment by friendly-bits** [comment]
I'd estimate probably up to 50-70 extra lines of code. Actually even a config option is unnecessary: simply detect ash version and disable the features automatically if it doesn't support process substitution.

**Comment by friendly-bits** [comment]
One question though: which was the first version of OpenWrt which had the updated dnsmasq? We should compare that to the first version which had ash support for process substitution. If these changes happened with the same version change then it's questionable whether implementing this sort makes sense.

**Comment by lynxthecat** [comment]
@Wizballs was the first to identify this: 

https://forum.openwrt.org/t/adblock-oisd-22-03-allows-you-to-use-huge-blocklists-with-dnsmasq/136413

https://thekelleys.org.uk/dnsmasq/CHANGELOG

**Comment by friendly-bits** [comment]
So the first Busybox version to support process substitution was 1.34.
OpenWrt 22.03 was the first version which had Busybox version with process substitution support.
22.03 was also the first version with the updated dnsmasq.

So basically OpenWrt versions 22.03 and higher already support all adblock-lean features, and all versions prior than that don't support neither process substitution nor blocklist compression nor decreased blocklist memory footprint. Not sure it makes sense to change the code in order to re-add support for versions on which adblock-lean won't be as memory-efficient. Maybe? What do you guys think? @Wizballs @lynxthecat @dave14305 @rickparrish

**Comment by lynxthecat** [comment]
There are often posts on the OpenWrt forum from variants of OpenWrt and often these are shutdown pretty quickly on the basis that support for something other than OpenWrt is sought from OpenWrt. I think like you were indicating above it makes sense to me to take some small measures to include compatibility where it won't hurt performance in OpenWrt, but this only stretches so far, and this, combined with the outdatedness of this ImmortalWrt version and lack of support for some of the key elements makes me think that taking extra steps is not warranted here.

**Comment by Wizballs** [comment]
Was it only the 'tee' command that is preventing it running on earlier busybox versions?

@hungtoong could you please try installing
coreutils-tee
and try adblock-lean again.

**Comment by Wizballs** [comment]
> earlier versions don't support neither process substitution nor blocklist compression nor decreased blocklist memory footprint

@friendly-bits intermediate compression should still work, just not the final Blocklist compression.  Interested to see if hungtoong can simply install coreutils-tee for this to work.

**Comment by friendly-bits** [comment]
> try installing package
> 'coreutils-tee'
> and try adblock-lean again

Unfortunately, this is not a limitation of `tee`. The limitation is in the Busybox ash command interpreter which in Busybox versions prior to 1.34 doesn't understand the syntax `>(...)` which is called process substitution. This syntax is not compliant to the POSIX standard, so technically ash doesn't actually have to implement it at all, but thankfully they did, which enabled us to make these beautiful long pipes. What @hungtoong could actually try is installing and using the `Bash` command interpreter to run adblock-lean. They would need to replace the "shebang": `#!/bin/sh /etc/rc.common` -> `#!/bin/bash /etc/rc.common`. I think (?) this may work.

**Comment by Wizballs** [comment]
@friendly-bits ok thanks good to know.  Potentially could include an optional command to replace the shebang (y/n) if this works.

**Comment by friendly-bits** [comment]
Since we have discovered that dnsmasq included with OpenWrt versions prior to 22.03 can not handle a large number of domains well, I think adding a workaround for this issue makes no sense. So this can be closed IMO.
