### ISSUE TITLE
Error: Directory '/tmp/dnsmasq.d' does not exist. Failed to detect dnsmasq directory or dnsmasq is not running.

### ISSUE THREAD

**Issue by jeffers3n** [lynxthecat/adblock-lean#85]
Error: Directory '/tmp/dnsmasq.d' does not exist. Failed to detect dnsmasq directory or dnsmasq is not running.

**Comment by lynxthecat** [comment]
As far as I understand, and @friendly-bits can hopefully confirm, this is an issue with OpenWrt in general right now - see: 

https://forum.openwrt.org/t/adblock-lean-set-up-adblock-using-dnsmasq-blocklist/157076/1481

**Comment by friendly-bits** [comment]
This is an issue with current OpenWrt snapshots. adblock-lean works fine on latest stable OpenWrt versions. I covered this in the forum, so I'll just copy-paste the response:

Indeed, the snapshots of OpenWrt have some changes which break adblock-lean (and other software) by removing the default dnsmasq directory setting. There is a pending [pull request 1](https://github.com/openwrt/openwrt/pull/16806) which, if accepted, should fix that. In the meantime, before we know where this is going, it probably doesn't make sense to change the code in adblock-lean. A workaround for people who are using a snapshot is this suggestion by [@dave14305](https://forum.openwrt.org/u/dave14305):

If you only have 1 dnsmasq instance, run:
```
uci set dhcp.@dnsmasq[0].confdir='/tmp/dnsmasq.d'
uci commit dhcp
service dnsmasq restart
```

One person on the forum replied that this workaround didn't work for them. @jeffers3n would be nice if you could test it and let us know the result. If it doesn't work, we can come up with a workaround in adblock-lean code.

**Comment by jeffers3n** [comment]
Tested, the issue has been resolved. Thank you very much!

uci set dhcp.@dnsmasq[0].confdir='/tmp/dnsmasq.d'
uci commit dhcp
service dnsmasq restart
